### ISSUE TITLE
Investigate making better error for lack of user context

### ISSUE THREAD

**Issue by carsongee** [carsongee/flask-htpasswd#17]
Per #16's resolution and comment

**Comment by bth5032** [comment]
I played around with this some more. I don't think there is an error in your code. I tried for an hour to reproduce the error I was getting with a more minimal flask program, but couldn't get it to happen. That makes me think it was something specific to our program.

My best guess is that it had something to do with flask-loginmanager being used elsewhere in the program. I did verify that if you do not include a user argument, you get a proper error: http://imgur.com/MWYxwnc. 

No issues on your end as far as I can verify, sorry for any confusion. I'll let you know if I learn anything else.

**Comment by carsongee** [comment]
Wow, thanks for digging in and figuring this out.  I appreciate the reporting and deep dive.

**Comment by bth5032** [comment]
No problem, thanks for making my life easier with the software!
