### ISSUE TITLE
Unexpected keyword argument 'user'

### ISSUE THREAD

**Issue by vidstige** [carsongee/flask-htpasswd#22]
Can't get basic auth to work. Keep getting the following. Using python3 and Flask==0.12.2

    TypeError: send_js() got an unexpected keyword argument 'user'

Please advice.

**Comment by carsongee** [comment]
If you want to post the code you're using I can be more specific, but I'm guessing your endpoint function is just missing an argument that the extensions adds, i.e. you may have something like:
```python
@app.route('/send_js/')
@htpasswd.required
def send_js():
    ...
```
and you just need to add a parameter that `@htpasswd.required` gives you so you can identify the user:
```python
@app.route('/send_js/')
@htpasswd.required
def send_js(user):
    ...
```
if you don't need the user object for your function, you can always just use an underscore or similar to identify that it isn't used, i.e.:
```python
@app.route('/send_js/')
@htpasswd.required
def send_js(_):
    ...
```

**Comment by vidstige** [comment]
Ah, it was probably because I didn't have the `user` argument in my function. Anyway, I rolled my own decorator in a few lines of python so problem solved. Perhaps this can be even more stressed in the README to make it easier to understand? I see now in the example there is a `user` argument, but missed it first time.
