### ISSUE TITLE
Repeatedly Asks For Password

### ISSUE THREAD

**Issue by hydroplosion** [carsongee/flask-htpasswd#23]
I'm trying to get this working, but authentication never succeeds. _htpasswd -v <file> user_ says the password is correct. I am also using flask_wtf if that matters. I only see 401 in the Apache access.log file. Most of my libraries are the latest, and Python is 3.5.

```
import datetime
from flask import Flask, flash, redirect, render_template
from flask_htpasswd import HtPasswdAuth
from flask_wtf import FlaskForm
from wtforms import PasswordField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

app = Flask(__name__)
app.config['SECRET_KEY'] = <key for csrf>
app.config['FLASK_HTPASSWD_PATH'] = '/path/to/.htpasswd'
app.config['FLASK_SECRET'] = "Blah blah!"
#app.config['FLASK_AUTH_ALL'] = True
htpasswd = HtPasswdAuth(app)

@app.route("/", methods=['GET', 'POST'])
@htpasswd.required

def myMethod(_):
    form = MyForm()
    return render_template('form.html', title='Form', form=form)

if __name__ == "__main__":
    app.run(debug=True)

class MyForm(FlaskForm):
    text = TextAreaField('a', validators=[DataRequired()])
    submit = SubmitField('submit')
```

**Comment by carsongee** [comment]
Can you paste the output you're seeing when you run this?  I was able to run it without any issue, i.e. login after I realized that I don't support `~` expansion of paths and get to an error due to `user` not being the arg for `myMethod`.  If there is an issue with the htpasswd file (finding it or parsing it properly, you should get an error in the output:
```
No htpasswd file loaded, please set `FLASK_HTPASSWD`or `FLASK_HTPASSWD_PATH` environment variable to a valid apache htpasswd file.
```

**Comment by hydroplosion** [comment]
I see nothing in the logs. I think it might be an apache config or mod_wsgi issue. 

Yep, needed 'WSGIPassAuthorization On' and only 'AuthType Basic' in the apache config.
